// ============================================================
// DATOS ESTÁTICOS — Mi Camino a la U
// Fuente: "Panorama Exhaustivo Educación Superior Chile 2026"
// Última verificación: febrero 2026
// ============================================================

import CARRERAS_JSON from './carreras.json';

import type {
  Beneficio,
  CalendarioItem,
  Carrera,
  Institucion,
  ViaIngreso,
} from '../types';

const CARRERAS_FULL = CARRERAS_JSON as unknown as Carrera[];

const normalize = (str?: string | null) =>
  String(str || '')
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

export { CARRERAS_FULL, normalize };

// ─── VÍAS DE INGRESO ───────────────────────────────────────

export const VIAS_INGRESO: ViaIngreso[] = [
  {
    id: 'paes',
    nombre: 'Admisión Centralizada (PAES)',
    icono: '🎓',
    desc: 'Postulación a través de la Plataforma Electrónica Única a las 47 universidades adscritas al Sistema de Acceso.',
    requisitos: [
      'Licencia de Enseñanza Media',
      'Inscripción en demre.cl',
      'Rendir PAES Regular (nov/dic) o PAES de Invierno (junio)',
    ],
    fuente: 'acceso.mineduc.cl',
  },
  {
    id: 'pace',
    nombre: 'Programa PACE',
    icono: '🏫',
    desc: 'Acceso garantizado para estudiantes del 15% superior de su establecimiento en colegios elegibles (alta vulnerabilidad).',
    requisitos: [
      'Pertenecer al 15% superior del establecimiento',
      'Colegio inscrito en el Programa PACE',
      'Puntaje ponderado PACE mínimo según universidad',
    ],
    fuente: 'pace.mineduc.cl',
  },
  {
    id: 'especial',
    nombre: 'Admisión Especial',
    icono: '⭐',
    desc: 'Cupos para perfiles específicos: personas con discapacidad, deportistas de alto rendimiento, etnias indígenas y talento artístico.',
    requisitos: [
      'Acreditar la condición específica',
      'Postular directamente en la universidad',
      'Cumplir requisitos institucionales',
    ],
    fuente: 'acceso.mineduc.cl/admision-especial',
  },
  {
    id: 'ip_cft',
    nombre: 'IP y CFT (Técnico-Profesional)',
    icono: '🔧',
    desc: 'Postulación directa en cada institución. No requiere PAES. Se considera NEM, RAP y experiencia laboral.',
    requisitos: [
      'Licencia de Enseñanza Media',
      'Postular directamente en la institución',
      'Experiencia laboral (mínimo 3 años favorece en algunos criterios)',
    ],
    fuente: 'acceso.mineduc.cl/tp',
  },
];

// ─── BENEFICIOS ESTUDIANTILES ──────────────────────────────
// Fuente: beneficiosestudiantiles.cl / chileatiende.gob.cl
// FUAS Segundo Período 2026: 12 febrero – 12 marzo

export const BENEFICIOS: Beneficio[] = [
  {
    id: 'gratuidad',
    nombre: 'Gratuidad',
    categoria: 'Gratuidad',
    resumen: 'Cubre matrícula y arancel real completo.',
    detalles:
      'Financia el 100% de la matrícula y el arancel real en instituciones adscritas. No genera deuda. Se mantiene mientras se cumplan los requisitos académicos y socioeconómicos.',
    requisitosRSH: 60,
    requisitoPuntaje: 0,
    requisitoNEM: 0,
    montoEstimado: 'Arancel real completo',
    compatible: ['baes'],
    instituciones: 'Universidades, IPs y CFTs adscritas a Gratuidad',
    fuente: 'gratuidad.cl',
    alerta: '⚠️ Verifica que tu institución esté adscrita en gratuidad.cl',
  },
  {
    id: 'bicentenario',
    nombre: 'Beca Bicentenario',
    categoria: 'Beca',
    resumen: 'Cubre el arancel de referencia.',
    detalles:
      'Financia hasta el arancel de referencia fijado por el MINEDUC. La diferencia entre el arancel real y el de referencia (brecha) puede quedar a cargo del estudiante.',
    requisitosRSH: 70,
    requisitoPuntaje: 510,
    requisitoNEM: 0,
    montoEstimado: 'Arancel de referencia (varía por carrera)',
    compatible: ['baes', 'cae'],
    instituciones: 'Universidades del CRUCH y privadas adscritas',
    fuente: 'beneficiosestudiantiles.cl',
  },
  {
    id: 'nuevo_milenio',
    nombre: 'Beca Nuevo Milenio',
    categoria: 'Beca',
    resumen: 'Apoyo al arancel en IP y CFT según tramos RSH.',
    detalles:
      'Financia parte del arancel de referencia en institutos profesionales y centros de formación técnica. El monto varía según el tramo de RSH (40%, 50% o 60% del arancel de referencia).',
    requisitosRSH: 70,
    requisitoPuntaje: 0,
    requisitoNEM: 5.0,
    montoEstimado: 'Hasta $850.000 anuales (según tramo)',
    compatible: ['baes', 'cae'],
    instituciones: 'IPs y CFTs acreditados',
    fuente: 'beneficiosestudiantiles.cl',
  },
  {
    id: 'jgm',
    nombre: 'Beca Juan Gómez Millas',
    categoria: 'Beca',
    resumen: 'Hasta $1.150.000 anuales para universidades privadas.',
    detalles:
      'Destinada a estudiantes en universidades privadas no pertenecientes al CRUCH. Cubre parte del arancel de referencia con un tope de $1.150.000 anuales.',
    requisitosRSH: 70,
    requisitoPuntaje: 485,
    requisitoNEM: 0,
    montoEstimado: 'Hasta $1.150.000 anuales',
    compatible: ['baes', 'cae'],
    instituciones: 'Universidades privadas acreditadas no CRUCH',
    fuente: 'beneficiosestudiantiles.cl',
  },
  {
    id: 'fscu',
    nombre: 'Fondo Solidario (FSCU)',
    categoria: 'Crédito',
    resumen: 'Crédito blando para universidades CRUCH.',
    detalles:
      'Crédito con tasa de interés real del 2% anual. El repago comienza al egresar y solo cuando se supera el umbral de ingresos. Exclusivo para universidades del CRUCH.',
    requisitosRSH: 80,
    requisitoPuntaje: 0,
    requisitoNEM: 0,
    montoEstimado: 'Hasta arancel de referencia',
    compatible: ['baes'],
    instituciones: 'Universidades del Consejo de Rectores (CRUCH)',
    fuente: 'chileatiende.gob.cl',
  },
  {
    id: 'cae',
    nombre: 'Crédito con Aval del Estado (CAE)',
    categoria: 'Crédito',
    resumen: 'Crédito bancario con garantía estatal.',
    detalles:
      'Financia hasta el arancel de referencia. Tasa de interés del 2% real anual. El repago se inicia al egresar. Disponible en instituciones acreditadas (IESS).',
    requisitosRSH: 100,
    requisitoPuntaje: 485,
    requisitoNEM: 0,
    montoEstimado: 'Hasta arancel de referencia',
    compatible: ['baes', 'bicentenario', 'jgm'],
    instituciones: 'Instituciones de Educación Superior acreditadas (IESS)',
    fuente: 'ingresa.cl',
    alerta: '⚠️ Genera deuda. Evalúa el monto de la brecha antes de solicitarlo.',
  },
  {
    id: 'baes',
    nombre: 'BAES (JUNAEB)',
    categoria: 'Apoyo',
    resumen: 'Apoyo de alimentación ~$45.000/mes.',
    detalles:
      'Beneficio de alimentación para estudiantes con beca o gratuidad vigente. Se entrega como tarjeta de alimentación para uso en establecimientos autorizados.',
    requisitosRSH: 60,
    requisitoPuntaje: 0,
    requisitoNEM: 0,
    montoEstimado: '~$45.000 mensuales',
    compatible: ['gratuidad', 'bicentenario', 'nuevo_milenio', 'jgm', 'fscu', 'cae'],
    instituciones: 'Cualquier IES con otro beneficio JUNAEB activo',
    fuente: 'junaeb.cl',
  },
];

// ─── CALENDARIO 2026 ────────────────────────────────────────

export const CALENDARIO: CalendarioItem[] = [
  {
    id: 'cal_inscripcion_paes_invierno',
    mes: 'Marzo 2026',
    titulo: 'Inscripción PAES de Invierno',
    desc: 'Apertura de inscripciones en demre.cl para la PAES de Invierno (rendición en junio). Disponible para quienes deseen rendir antes de la PAES Regular.',
    estado: 'activo',
    categoria: 'PAES',
    link: 'https://demre.cl',
  },
  {
    id: 'cal_fuas',
    mes: 'Feb – Mar 2026',
    titulo: '⚠️ FUAS: 2° Período de Postulación',
    desc: 'Del 12 de febrero al 12 de marzo. Postula a Gratuidad, Becas y Créditos en portal.becasycreditos.cl. No pierdas el plazo.',
    estado: 'activo',
    categoria: 'Becas',
    link: 'https://portal.becasycreditos.cl',
  },
  {
    id: 'cal_matricula_2da',
    mes: 'Enero 2026',
    titulo: 'Matrícula 2ª Selección',
    desc: 'Proceso de matrícula para postulantes seleccionados en segunda vuelta del Sistema de Acceso 2026.',
    estado: 'pasado',
    categoria: 'Matricula',
    link: 'https://acceso.mineduc.cl',
  },
  {
    id: 'cal_resultados',
    mes: '19 Ene 2026',
    titulo: 'Resultados de Selección 2026',
    desc: 'Publicación oficial de resultados. Los seleccionados pueden ver su carrera y universidad asignada en el portal de acceso.',
    estado: 'pasado',
    categoria: 'Resultados',
    link: 'https://acceso.mineduc.cl',
  },
  {
    id: 'cal_paes_invierno',
    mes: 'Junio 2026',
    titulo: 'PAES de Invierno',
    desc: 'Rendición de la PAES de Invierno. Alternativa a la PAES Regular para quienes necesiten mejorar puntaje o no pudieron rendir en noviembre.',
    estado: 'pendiente',
    categoria: 'PAES',
    link: 'https://demre.cl',
  },
  {
    id: 'cal_inscripcion_regular',
    mes: 'Agosto 2026',
    titulo: 'Inscripción PAES Regular 2027',
    desc: 'Apertura de inscripciones en demre.cl para la PAES Regular del proceso 2027. Costos: 1 prueba $16.650 / 2 pruebas $30.475 / 3 o más $44.300.',
    estado: 'pendiente',
    categoria: 'PAES',
    link: 'https://demre.cl',
  },
  {
    id: 'cal_paes_regular',
    mes: 'Nov – Dic 2026',
    titulo: 'PAES Regular 2027',
    desc: 'Rendición de la PAES Regular. Pruebas disponibles: Competencia Lectora, M1, M2 (electiva), Ciencias (electiva), Historia y Cs. Sociales (electiva).',
    estado: 'pendiente',
    categoria: 'PAES',
    link: 'https://demre.cl',
  },
  {
    id: 'cal_postulacion_2027',
    mes: 'Dic 2026',
    titulo: 'Postulación Sistema de Acceso 2027',
    desc: 'Apertura de postulaciones a las 47 universidades adscritas a través de la Plataforma Electrónica Única.',
    estado: 'pendiente',
    categoria: 'Postulacion',
    link: 'https://acceso.mineduc.cl',
  },
];

// ─── INSTITUCIONES (47 UNIVERSIDADES ADSCRITAS 2026) ───────
// Fuente: acceso.mineduc.cl — proceso 2026

export const INSTITUCIONES: Institucion[] = [
  // CRUCH — Universidades Estatales
  { id: 'uchile', nombre: 'Universidad de Chile', sigla: 'UCH', tipo: 'CRUCH', region: 'Metropolitana', acreditacion: 7, gratuidad: true, pace: true, link: 'uchile.cl' },
  { id: 'usach', nombre: 'Universidad de Santiago de Chile', sigla: 'USACH', tipo: 'CRUCH', region: 'Metropolitana', acreditacion: 7, gratuidad: true, pace: true, link: 'usach.cl' },
  { id: 'umce', nombre: 'U. Metropolitana de Ciencias de la Educación', sigla: 'UMCE', tipo: 'CRUCH', region: 'Metropolitana', acreditacion: 5, gratuidad: true, pace: true, link: 'umce.cl' },
  { id: 'utem', nombre: 'Universidad Tecnológica Metropolitana', sigla: 'UTEM', tipo: 'CRUCH', region: 'Metropolitana', acreditacion: 5, gratuidad: true, pace: true, link: 'utem.cl' },
  { id: 'uv', nombre: 'Universidad de Valparaíso', sigla: 'UV', tipo: 'CRUCH', region: 'Valparaíso', acreditacion: 6, gratuidad: true, pace: true, link: 'uv.cl' },
  { id: 'upla', nombre: 'Universidad de Playa Ancha', sigla: 'UPLA', tipo: 'CRUCH', region: 'Valparaíso', acreditacion: 4, gratuidad: true, pace: true, link: 'upla.cl' },
  { id: 'utfsm', nombre: 'Universidad Técnica Federico Santa María', sigla: 'USM', tipo: 'CRUCH', region: 'Valparaíso', acreditacion: 6, gratuidad: true, pace: true, link: 'usm.cl' },
  { id: 'udec', nombre: 'Universidad de Concepción', sigla: 'UdeC', tipo: 'CRUCH', region: 'Bío-Bío', acreditacion: 7, gratuidad: true, pace: true, link: 'udec.cl' },
  { id: 'ubiobio', nombre: 'Universidad del Bío-Bío', sigla: 'UBB', tipo: 'CRUCH', region: 'Bío-Bío', acreditacion: 5, gratuidad: true, pace: true, link: 'ubiobio.cl' },
  { id: 'ufro', nombre: 'Universidad de La Frontera', sigla: 'UFRO', tipo: 'CRUCH', region: 'La Araucanía', acreditacion: 6, gratuidad: true, pace: true, link: 'ufrontera.cl' },
  { id: 'ulagos', nombre: 'Universidad de Los Lagos', sigla: 'ULagos', tipo: 'CRUCH', region: 'Los Lagos', acreditacion: 4, gratuidad: true, pace: true, link: 'ulagos.cl' },
  { id: 'uach', nombre: 'Universidad Austral de Chile', sigla: 'UACh', tipo: 'CRUCH', region: 'Los Ríos', acreditacion: 7, gratuidad: true, pace: true, link: 'uach.cl' },
  { id: 'umag', nombre: 'Universidad de Magallanes', sigla: 'UMAG', tipo: 'CRUCH', region: 'Magallanes', acreditacion: 4, gratuidad: true, pace: true, link: 'umag.cl' },
  { id: 'utalca', nombre: 'Universidad de Talca', sigla: 'UTalca', tipo: 'CRUCH', region: 'Maule', acreditacion: 6, gratuidad: true, pace: true, link: 'utalca.cl' },
  { id: 'ucm', nombre: 'Universidad Católica del Maule', sigla: 'UCM', tipo: 'CRUCH', region: 'Maule', acreditacion: 5, gratuidad: true, pace: true, link: 'ucm.cl' },
  { id: 'ucsc', nombre: 'U. Católica de la Santísima Concepción', sigla: 'UCSC', tipo: 'CRUCH', region: 'Bío-Bío', acreditacion: 5, gratuidad: true, pace: true, link: 'ucsc.cl' },
  { id: 'ucn', nombre: 'Universidad Católica del Norte', sigla: 'UCN', tipo: 'CRUCH', region: 'Antofagasta', acreditacion: 5, gratuidad: true, pace: true, link: 'ucn.cl' },
  { id: 'uta', nombre: 'Universidad de Tarapacá', sigla: 'UTA', tipo: 'CRUCH', region: 'Arica y Parinacota', acreditacion: 5, gratuidad: true, pace: true, link: 'uta.cl' },
  { id: 'unap', nombre: 'Universidad Arturo Prat', sigla: 'UNAP', tipo: 'CRUCH', region: 'Tarapacá', acreditacion: 4, gratuidad: true, pace: true, link: 'unap.cl' },
  { id: 'uan', nombre: 'Universidad de Antofagasta', sigla: 'UA', tipo: 'CRUCH', region: 'Antofagasta', acreditacion: 5, gratuidad: true, pace: true, link: 'uantof.cl' },
  { id: 'uls', nombre: 'Universidad de La Serena', sigla: 'ULS', tipo: 'CRUCH', region: 'Coquimbo', acreditacion: 5, gratuidad: true, pace: true, link: 'userena.cl' },
  { id: 'uda', nombre: 'Universidad de Atacama', sigla: 'UDA', tipo: 'CRUCH', region: 'Atacama', acreditacion: 4, gratuidad: true, pace: true, link: 'uda.cl' },
  { id: 'uohiggins', nombre: "Universidad de O'Higgins", sigla: "UOH", tipo: 'CRUCH', region: "O'Higgins", acreditacion: 4, gratuidad: true, pace: true, link: 'uoh.cl' },
  { id: 'uaysen', nombre: 'Universidad de Aysén', sigla: 'UAysén', tipo: 'CRUCH', region: 'Aysén', acreditacion: 3, gratuidad: true, pace: true, link: 'uaysen.cl' },
  // CRUCH — Pontifica/Privada histórica
  { id: 'puc', nombre: 'Pontificia Universidad Católica de Chile', sigla: 'PUC', tipo: 'CRUCH', region: 'Metropolitana', acreditacion: 7, gratuidad: true, pace: false, link: 'uc.cl' },
  { id: 'pucv', nombre: 'Pontificia Universidad Católica de Valparaíso', sigla: 'PUCV', tipo: 'CRUCH', region: 'Valparaíso', acreditacion: 7, gratuidad: true, pace: true, link: 'pucv.cl' },
  // Privadas adscritas al Sistema de Acceso
  { id: 'uai', nombre: 'Universidad Adolfo Ibáñez', sigla: 'UAI', tipo: 'Privada', region: 'Metropolitana', acreditacion: 5, gratuidad: false, pace: false, link: 'uai.cl' },
  { id: 'uah', nombre: 'Universidad Alberto Hurtado', sigla: 'UAH', tipo: 'Privada', region: 'Metropolitana', acreditacion: 5, gratuidad: true, pace: true, link: 'uahurtado.cl' },
  { id: 'unab', nombre: 'Universidad Andrés Bello', sigla: 'UNAB', tipo: 'Privada', region: 'Metropolitana', acreditacion: 5, gratuidad: false, pace: false, link: 'unab.cl' },
  { id: 'uautonoma', nombre: 'Universidad Autónoma de Chile', sigla: 'UA', tipo: 'Privada', region: 'Metropolitana', acreditacion: 4, gratuidad: false, pace: false, link: 'uautonoma.cl' },
  { id: 'ucentral', nombre: 'Universidad Central de Chile', sigla: 'UCEN', tipo: 'Privada', region: 'Metropolitana', acreditacion: 4, gratuidad: false, pace: false, link: 'ucentral.cl' },
  { id: 'udelas_americas', nombre: 'Universidad de Las Américas', sigla: 'UDLA', tipo: 'Privada', region: 'Metropolitana', acreditacion: 4, gratuidad: false, pace: false, link: 'udla.cl' },
  { id: 'ulosandes', nombre: 'Universidad de Los Andes', sigla: 'UANDES', tipo: 'Privada', region: 'Metropolitana', acreditacion: 5, gratuidad: false, pace: false, link: 'uandes.cl' },
  { id: 'udd', nombre: 'Universidad del Desarrollo', sigla: 'UDD', tipo: 'Privada', region: 'Metropolitana', acreditacion: 5, gratuidad: false, pace: false, link: 'udd.cl' },
  { id: 'udp', nombre: 'Universidad Diego Portales', sigla: 'UDP', tipo: 'Privada', region: 'Metropolitana', acreditacion: 5, gratuidad: false, pace: false, link: 'udp.cl' },
  { id: 'ufinis', nombre: 'Universidad Finis Terrae', sigla: 'UFT', tipo: 'Privada', region: 'Metropolitana', acreditacion: 4, gratuidad: false, pace: false, link: 'uft.cl' },
  { id: 'umayor', nombre: 'Universidad Mayor', sigla: 'UMAYOR', tipo: 'Privada', region: 'Metropolitana', acreditacion: 4, gratuidad: false, pace: false, link: 'umayor.cl' },
  { id: 'uss', nombre: 'Universidad San Sebastián', sigla: 'USS', tipo: 'Privada', region: 'Metropolitana', acreditacion: 5, gratuidad: false, pace: false, link: 'uss.cl' },
  { id: 'ust', nombre: 'Universidad Santo Tomás', sigla: 'UST', tipo: 'Privada', region: 'Metropolitana', acreditacion: 4, gratuidad: false, pace: false, link: 'santotomas.cl' },
  { id: 'uvina', nombre: 'Universidad de Viña del Mar', sigla: 'UVM', tipo: 'Privada', region: 'Valparaíso', acreditacion: 4, gratuidad: false, pace: false, link: 'uvm.cl' },
  { id: 'uahc', nombre: 'U. Academia de Humanismo Cristiano', sigla: 'UAHC', tipo: 'Privada', region: 'Metropolitana', acreditacion: 4, gratuidad: true, pace: true, link: 'academia.cl' },
  { id: 'ubo', nombre: 'Universidad Bernardo O\'Higgins', sigla: 'UBO', tipo: 'Privada', region: 'Metropolitana', acreditacion: 4, gratuidad: false, pace: false, link: 'ubo.cl' },
  { id: 'ucsh', nombre: 'Universidad Católica Silva Henríquez', sigla: 'UCSH', tipo: 'Privada', region: 'Metropolitana', acreditacion: 4, gratuidad: true, pace: true, link: 'ucsh.cl' },
  { id: 'ulascondes', nombre: 'Universidad Las Condes', sigla: 'ULC', tipo: 'Privada', region: 'Metropolitana', acreditacion: 3, gratuidad: false, pace: false, link: 'ulascondes.cl' },
  { id: 'uisek', nombre: 'Universidad Internacional SEK', sigla: 'UISEK', tipo: 'Privada', region: 'Metropolitana', acreditacion: 3, gratuidad: false, pace: false, link: 'uisek.cl' },
  { id: 'upedro', nombre: 'Universidad Pedro de Valdivia', sigla: 'UPV', tipo: 'Privada', region: 'Metropolitana', acreditacion: 3, gratuidad: false, pace: false, link: 'upv.cl' },
  { id: 'ucervantes', nombre: 'Universidad Miguel de Cervantes', sigla: 'UMC', tipo: 'Privada', region: 'Metropolitana', acreditacion: 3, gratuidad: false, pace: false, link: 'ucervantes.cl' },
  // Principales IPs y CFTs (postulación directa)
  { id: 'inacap', nombre: 'INACAP', sigla: 'INACAP', tipo: 'IP', region: 'Nacional', acreditacion: 5, gratuidad: true, pace: false, link: 'inacap.cl' },
  { id: 'duoc', nombre: 'Duoc UC', sigla: 'DUOC', tipo: 'IP', region: 'Nacional', acreditacion: 6, gratuidad: false, pace: false, link: 'duoc.cl' },
  { id: 'ipss', nombre: 'IP Santo Tomás', sigla: 'IPST', tipo: 'IP', region: 'Nacional', acreditacion: 5, gratuidad: false, pace: false, link: 'santotomas.cl' },
  { id: 'cft_lota', nombre: 'CFT Lota Arauco', sigla: 'CFTA', tipo: 'CFT', region: 'Bío-Bío', acreditacion: 3, gratuidad: true, pace: false, link: 'cftalotaarauco.cl' },
];

// ─── CARRERAS (MUESTRA REPRESENTATIVA) ─────────────────────
// Datos de corte basados en proceso 2024. Actualizar con 2026.

export const CARRERAS: Carrera[] = [
  {
    id: 'medicina_uchile',
    nombre: 'Medicina',
    area: 'Salud',
    institucion: 'Universidad de Chile',
    tipo: 'Universidad',
    region: 'Metropolitana',
    vacantes: 130,
    corte2024: 839,
    corte2023: 842,
    coeficientes: { nem: 0.2, ranking: 0.2, lc: 0.2, m1: 0.2, m2: 0, ciencias: 0.2, historia: 0 },
    duracion: '7 años',
    grado: 'Título profesional + Licenciatura',
    arancel: 8420000,
    arancelReferencia: 5497158,
    acreditacion: 7,
    gratuidad: true,
  },
  {
    id: 'ingcivil_usach',
    nombre: 'Ingeniería Civil',
    area: 'Tecnología',
    institucion: 'Universidad de Santiago de Chile',
    tipo: 'Universidad',
    region: 'Metropolitana',
    vacantes: 130,
    corte2024: 705,
    corte2023: 712,
    coeficientes: { nem: 0.2, ranking: 0.2, lc: 0.1, m1: 0.3, m2: 0.2, ciencias: 0, historia: 0 },
    duracion: '6 años',
    grado: 'Título profesional + Licenciatura',
    arancel: 4890000,
    arancelReferencia: 3940000,
    acreditacion: 6,
    gratuidad: true,
  },
  {
    id: 'derecho_udp',
    nombre: 'Derecho',
    area: 'Derecho',
    institucion: 'Universidad Diego Portales',
    tipo: 'Universidad',
    region: 'Metropolitana',
    vacantes: 180,
    corte2024: 615,
    corte2023: 608,
    coeficientes: { nem: 0.2, ranking: 0.2, lc: 0.3, m1: 0.1, m2: 0, ciencias: 0, historia: 0.2 },
    duracion: '5 años',
    grado: 'Título profesional + Licenciatura',
    arancel: 5920000,
    arancelReferencia: 3467418,
    acreditacion: 5,
    gratuidad: false,
  },
  {
    id: 'pedagogia_uchile',
    nombre: 'Pedagogía en Educación Básica',
    area: 'Educación',
    institucion: 'Universidad de Chile',
    tipo: 'Universidad',
    region: 'Metropolitana',
    vacantes: 60,
    corte2024: 580,
    corte2023: 572,
    coeficientes: { nem: 0.2, ranking: 0.3, lc: 0.3, m1: 0.1, m2: 0, ciencias: 0, historia: 0.1 },
    duracion: '5 años',
    grado: 'Título + Licenciatura',
    arancel: 3680000,
    arancelReferencia: 2847000,
    acreditacion: 7,
    gratuidad: true,
  },
  {
    id: 'enfermeria_udec',
    nombre: 'Enfermería',
    area: 'Salud',
    institucion: 'Universidad de Concepción',
    tipo: 'Universidad',
    region: 'Bío-Bío',
    vacantes: 80,
    corte2024: 618,
    corte2023: 622,
    coeficientes: { nem: 0.2, ranking: 0.2, lc: 0.2, m1: 0.1, m2: 0, ciencias: 0.3, historia: 0 },
    duracion: '5 años',
    grado: 'Título profesional + Licenciatura',
    arancel: 4250000,
    arancelReferencia: 3467418,
    acreditacion: 7,
    gratuidad: true,
  },
  {
    id: 'ingcomercial_puc',
    nombre: 'Ingeniería Comercial',
    area: 'Negocios',
    institucion: 'Pontificia U. Católica de Chile',
    tipo: 'Universidad',
    region: 'Metropolitana',
    vacantes: 360,
    corte2024: 748,
    corte2023: 752,
    coeficientes: { nem: 0.2, ranking: 0.2, lc: 0.15, m1: 0.25, m2: 0.2, ciencias: 0, historia: 0 },
    duracion: '5 años',
    grado: 'Título profesional + Licenciatura',
    arancel: 7280000,
    arancelReferencia: 4312000,
    acreditacion: 7,
    gratuidad: true,
  },
  {
    id: 'psicologia_udec',
    nombre: 'Psicología',
    area: 'Ciencias Sociales',
    institucion: 'Universidad de Concepción',
    tipo: 'Universidad',
    region: 'Bío-Bío',
    vacantes: 75,
    corte2024: 595,
    corte2023: 590,
    coeficientes: { nem: 0.2, ranking: 0.2, lc: 0.3, m1: 0.1, m2: 0, ciencias: 0, historia: 0.2 },
    duracion: '5 años',
    grado: 'Título profesional + Licenciatura',
    arancel: 3980000,
    arancelReferencia: 3100000,
    acreditacion: 6,
    gratuidad: true,
  },
  {
    id: 'tecnico_enfermeria_inacap',
    nombre: 'Técnico en Enfermería',
    area: 'Salud',
    institucion: 'INACAP',
    tipo: 'IP',
    region: 'Nacional',
    vacantes: 200,
    corte2024: 0,
    corte2023: 0,
    coeficientes: { nem: 0.5, ranking: 0.5, lc: 0, m1: 0, m2: 0, ciencias: 0, historia: 0 },
    duracion: '2.5 años',
    grado: 'Título técnico de nivel superior',
    arancel: 2100000,
    arancelReferencia: 1842000,
    acreditacion: 5,
    gratuidad: true,
  },
  {
    id: 'ingcivil_ufro',
    nombre: 'Ingeniería Civil en Informática',
    area: 'Tecnología',
    institucion: 'Universidad de La Frontera',
    tipo: 'Universidad',
    region: 'La Araucanía',
    vacantes: 60,
    corte2024: 630,
    corte2023: 625,
    coeficientes: { nem: 0.2, ranking: 0.2, lc: 0.1, m1: 0.3, m2: 0.2, ciencias: 0, historia: 0 },
    duracion: '6 años',
    grado: 'Título profesional + Licenciatura',
    arancel: 3850000,
    arancelReferencia: 3200000,
    acreditacion: 6,
    gratuidad: true,
  },
  {
    id: 'trabajo_social_umce',
    nombre: 'Trabajo Social',
    area: 'Ciencias Sociales',
    institucion: 'U. Metropolitana de Ciencias de la Educación',
    tipo: 'Universidad',
    region: 'Metropolitana',
    vacantes: 50,
    corte2024: 540,
    corte2023: 535,
    coeficientes: { nem: 0.25, ranking: 0.25, lc: 0.3, m1: 0.1, m2: 0, ciencias: 0, historia: 0.1 },
    duracion: '5 años',
    grado: 'Título profesional + Licenciatura',
    arancel: 2980000,
    arancelReferencia: 2600000,
    acreditacion: 5,
    gratuidad: true,
  },
];

// ─── COSTOS INSCRIPCIÓN PAES 2026 ──────────────────────────

export const COSTOS_PAES = {
  unaPrueba: 16650,
  dosPruebas: 30475,
  tresMas: 44300,
  becaPAES: 'Estudiantes de colegios con subvención estatal pueden solicitar la Beca PAES para eximirse del pago.',
};

// ─── REQUISITOS HABILITACIÓN PEDAGOGÍAS ────────────────────

export const REQUISITOS_PEDAGOGIA = {
  percentilPAES: 60,
  percentilRanking: 20,
  descripcion: 'Para estudiar pedagogía debes cumplir al menos uno: estar en el percentil 60 superior en la PAES, pertenecer al 20% superior del ranking de notas, o haber aprobado un Programa de Atracción de Talento Pedagógico (PAT).',
};
